### PR TITLE
Quote value starting with % to validate YML

### PR DESCRIPTION
**Pull request by ataylorme**
Addresses #166

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rvodden** [comment]
If this passes I'll merge it. Thank you for the super quick PR!

**Comment by ataylorme** [comment]
Great, thanks @rvodden. I'm re-running my tests with the PR branch and will let you know how that goes.

**Comment by ataylorme** [comment]
@rvodden any chance of tagging a minor version so I can keep using WordHat proper instead of a fork?

**Comment by rvodden** [comment]
That's one for @PaulGibbs

**Comment by paulgibbs** [comment]
I can sort out a release in the morning (I’m in the UK). 

--- 
Paul Gibbs

**Comment by ataylorme** [comment]
Thanks Paul - you guys are great at being right on top of it :-) I'm not in that big of a rush so later than the morning for you is okay as well.

**Pull request merged**
