### PR TITLE
The Selenium2 driver for Mink is a dependency

### PR DESCRIPTION
**Pull request by johnbillion**
The Selenium2 driver for Mink is a dependency, not a development dependency.

### CODE REVIEW

**Comment by stephenharris** [comment]
Selenium2 driver for Mink isn't strictly speaking a dependency, as you can use any of the other drivers. I've only used Selenium2 & Goutte, but WordHat is as far as I know driver agnostic. But if we're not going to have Selenium2 as dependency, then we probably shouldn't have Goutte either.

We could either add Selenium2, or remove Goutte (move it to a dev-dependency), add them both as suggested packages and update the documentation. @paulgibbs - what do you think?

**Comment by paulgibbs** [comment]
For WordHat development, I would like it to be tested with Selenium and Goutte drivers for Mink.
For release, I don't mind, but I don't want this targeted at Behat experts. I want WordHat to be approachable to WordPress developers.

Right now, new users will follow https://wordhat.info/installation/index.html and there is intention to write a follow-up that has the user implement a WordPress-specific "Hello World" that they can connect to their site, run the test, and have it pass. For this, I think Goutte is the simplest way to get this done.

So: we can move Goutte out of dependencies into dev-dependencies, but the Installation document will need us to tell the User to install Goutte. We can keep Selenium out of dev-dependencies.

**Comment by paulgibbs** [comment]
> So: we can move Goutte out of dependencies into dev-dependencies, but the Installation document will need us to tell the User to install Goutte. We can keep Selenium out of dev-dependencies.

@stephenharris Does that sound good to you?

**Comment by stephenharris** [comment]
Yes, except we'd want the selenium driver in the dev-dependencies, since we are using it in our tests. I'll open a PR to address `composer.json` and also update the documentation.

**Comment by paulgibbs** [comment]
👍

**Comment by paulgibbs** [comment]
We're going to move Goutte into dev-deps, and Selenium in dev-deps, and update the tutorial doc and have that install Goutte at the same time as WordHat.

Thanks for this PR @johnbillion, I am going to close the request so we can proceed as above. ^

**Comment by johnbillion** [comment]
:+1:

**Pull request closed without merging**
