### PR TITLE
Add a step for adding a widget to a sidebar

### PR DESCRIPTION
**Pull request by stephenharris**
## Description

Defines a step for adding a widget to a sidebar, e.g.

   > Given I have the "RSS" widget in "Widget Area"
   > | Title   | Url                              | Items   |
   > | My feed | https://wordpress.org/news/feed/ | 3       

Adds a new element for the WP-Cli and WP API drivers to support this step.

It also adds `export WP_CLI_STRICT_ARGS_MODE=1` to the set up. In WP-Cli 'strict' mode allows you to use the `--url` argument multiple times. By default `--url` is a global parameter that refers to the site URL, but it may also be an argument to the command being run (see`widget.feature` for an example). 

Strict mode allows you to distinguish between the two: `--url` before the command refers to the [global parameter](https://make.wordpress.org/cli/handbook/config/#global-parameters) and `--url` after the command is interpreted to be an argument of that command. (See: https://make.wordpress.org/cli/handbook/config/#environment-variables )

## Motivation and context
To facilitate the testing of widgets and/or widget visibility.

## How has this been tested?
Yes, manually and on Travis. `widget.feature` has been added to support this new feature.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by paulgibbs** [comment]
I assume I'd also need to set WP_CLI_STRICT_ARGS_MODE locally when running these? If so, how do you feel about setting it in the WP-CLI driver when we shell out to run the WP-CLI command?

**Comment by paulgibbs** [comment]
Apart from that, everything looks fine and amazing :)

**Comment by stephenharris** [comment]
Good point - yes I think we should have the driver to do it. I'll update the PR later today.

**Comment by paulgibbs** [comment]
Great work!

**Pull request merged**
