### PR TITLE
Add a step which makes the 'Howdy' name accessible.

### PR DESCRIPTION
**Pull request by rvodden**
## Description
In order to effectively test issue #126 its handy to be able to get easily to the authenticated user name on the toolbar.

## Related issue
https://github.com/paulgibbs/behat-wordpress-extension/issues/126

## Motivation and context
I'd like to be able to test the fixes for #126.

## How has this been tested?
I've created a new scenario in user.features - see commit 48b9cf2

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by paulgibbs** [comment]
I'm looking at #126 before I consider merging this. Please leave it unmerged for now.

**Comment by rvodden** [comment]
This is a possible fix for #126. The root cause, as I saw it l, was that
user_nicename was being used as a slug, but is an optional field. Switching
to user_login means the field is always populated; user_email would be just
as good.

**Comment by paulgibbs** [comment]
This PR has value, but I'm not going to merge it directly. I think I've fixed the root issue described in #126, i'd appreciate your feedback over there if it works.

* I'm ok with making that "Howdy" menu's name accessible.
* I think the Toolbar Element is a better location than putting it inside the AdminPage object, given if the toolbar's not showing, then it won't be on the page. Pretty nit picking, though. :)
* We need to come up with something better than "then the username should be X" for the step. Something like "then the toolbar should show I am authenticated as X". ??

Going to wait for your feedback and when I get time, either cherry-pick bits out if I can, or copy/paste into a new branch and throw it in.

**Comment by rvodden** [comment]
I'm completely with you. I've got some time this week, so I'm happy to modify my PR to match your suggestions and let you focus on moving house? Should be able to have something for you by Thursday,

**Comment by paulgibbs** [comment]
👍

**Comment by rvodden** [comment]
I've completed the steps as we agreed (sorry this was so slow):
- [X] I'm ok with making that "Howdy" menu's name accessible.
- [X] I think the Toolbar Element is a better location than putting it inside the AdminPage object, given if the toolbar's not showing, then it won't be on the page. Pretty nit picking, though. :)
- [X] We need to come up with something better than "then the username should be X" for the step. Something like "then the toolbar should show I am authenticated as X". ??

However the wpphp build is still failing on travis owing to the most recent comment on #126. I'll demonstrate that in the next couple of commits.

**Comment by rvodden** [comment]
So with the fix for #126 in everything passes. I'm happy to roll that back and submit a separate pull request if we want to keep things clean?

**Comment by rvodden** [comment]
So with the fix in for #126 on WPPHP everything passes. I've also removed my original proposed fix for #126 on WPCLI ( which was to return the login, rather than the nicename ) as that is no longer necessary - and everything is still passing. I'm happy, if you'd like to keep things clean, to remove the WPPHP #126 issue and submit it as a separate pull request?

**Comment by paulgibbs** [comment]
Will look at this this weekend. First glance, it looks good :)

**Comment by stephenharris** [comment]
Looks good to me :). Much neater to have it in the the toolbar and I agree with the step wording changed.

**Comment by paulgibbs** [comment]
This was really good @rvodden, thanks for working on it. I've merged it in into master, with a few tweaks (10cd7e527a877c61f304f489eaea888127f445e0).

**Comment by rvodden** [comment]
No worries. I'll have a look at #128 next. If there's anything else you'd like me to look at in the runup to 1.0 give me a shout. I'm more than happy to put some effort into this. It really is a super useful tool for me.

**Pull request merged**
