### PR TITLE
Driver interface refactor

### PR DESCRIPTION
**Pull request by paulgibbs**
## Description

> As noted via e-mail, the Driver acts as an interface for communication between Behat and WordPress (creating, deleting, asserting properties of) content/users/options/terms etc.
> The Driver, therefore, could grow quite large. One suggestion is to compartmentalize each WordPress 'entity' (content, users, etc)

This PR does that.

## Related issue

See #21

## Motivation and context
The Driver(s) were getting too large, and would only grow bigger as we implement planned features. They also did multiple things in the same class, which breaks the single responsibility principle.

For what it's worth, pre-change, Scrutinzer-CI ranked the project as 9.11, and post-change, it ranks at 9.47. Most of the improvement in it's rating comes from simplifying the monolithic driver classes.

## How has this been tested?
Tested locally and on Travis-CI. It does pass on Travis-CI but the log-in problems -- see #47 -- cause unrelated failures.

The breaking changes are backwards-compatible supported until 1.0.0. In fact, at the current moment, the main project continues to use those backwards-compatible methods to prove that they work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by paulgibbs** [comment]
I opened this so I can run scrutiniser against it, so I can use its opinion as a yardstick whether the changes make the code more "Better" or not.

**Comment by stephenharris** [comment]
Looks good. One suggestion, could `create` return the same thing as `get` - i.e. you `get` what you just created. It will save having to make separate calls to get the thing you just created.

I know it's mid-development, but I noticed we can only get something by its ID rather than a human-friendly name (e.g. term name, post name, username/email etc). In Behat we'll be mostly referring to items by a human-friendly name (e.g `Given "Hello World!" has the post tag "foobar"` or `When I click "quick edit" in the action links for "Hello World"`). Is `get()` going to support that?

**Comment by paulgibbs** [comment]
good idea about create / get, sounds good.

yeah get working on IDs at the moment. I know other stuff required especially for content. going to have a look at that a bit more detail and try come up with a more flexible approach

**Comment by paulgibbs** [comment]
I've updated WPCLI elements to return get() from create().

I'm going to do other drivers' before backwards compatibility.

**Pull request merged**
